# Generated by Django 5.2.2 on 2025-06-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_ts', models.DateTimeField()),
                ('user_url', models.URLField()),
            ],
            options={
                'unique_together': {('snapshot_ts', 'user_url')},
            },
        ),
        migrations.CreateModel(
            name='BlueprintSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_ts', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('favourites', models.IntegerField()),
                ('total_comments', models.IntegerField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitoring.blueprint')),
            ],
            options={
                'unique_together': {('snapshot_ts', 'blueprint')},
            },
        ),
        migrations.CreateModel(
            name='CommentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_ts', models.DateTimeField()),
                ('comment_id', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('created_utc', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_snapshots', to='monitoring.blueprint')),
            ],
            options={
                'unique_together': {('snapshot_ts', 'blueprint', 'comment_id')},
            },
        ),
    ]
