# Generated by Django 5.2.6 on 2026-06-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_snapshotrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50)),
                ('handled', models.BooleanField(default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_statuses', to='monitoring.blueprint')),
            ],
            options={
                'verbose_name_plural': 'comment statuses',
                'unique_together': {('blueprint', 'comment_id')},
            },
        ),
    ]
