# Generated by Django 5.2.6 on 2026-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_commentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.URLField(unique=True)),
                ('disqus_name', models.CharField(blank=True, default='', max_length=100)),
                ('alerts_enabled', models.BooleanField(default=False)),
                ('alert_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'user settings',
            },
        ),
    ]
