# Generated by Django 5.2.6 on 2026-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
